<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Api\V1\LanguageController;
use App\Http\Controllers\Api\V1\DialectController;
use App\Http\Controllers\Api\V1\ContributionController;
use App\Http\Controllers\Api\V1\ReviewController;
use App\Http\Controllers\Api\V1\CourseController;
use App\Http\Controllers\Api\V1\ExportController;
use App\Http\Controllers\Api\V1\AiController;
use App\Http\Controllers\Api\V1\DictionaryController;
use App\Http\Controllers\Api\V1\SourceController;
use App\Http\Controllers\Api\V1\AudioController;
use App\Http\Controllers\Api\V1\CommunityController;
use App\Http\Controllers\Api\V1\LearningController;
use App\Http\Controllers\Api\V1\AnalyticsController;
use App\Http\Controllers\Api\V1\SearchController;
use App\Http\Controllers\Api\V1\StatisticsController;
use App\Http\Controllers\Api\V1\LinguisticsController;
use App\Http\Controllers\Api\V1\AuditLogController;

Route::prefix('v1')->middleware('throttle:api')->group(function () {
    Route::apiResource('languages', LanguageController::class)->only(['index', 'show']);
    Route::get('languages/{language}/dialects', [DialectController::class, 'index']);
    Route::get('contributions', [ContributionController::class, 'index']);
    Route::get('contributions/{contribution}', [ContributionController::class, 'show']);
    Route::get('sources', [SourceController::class, 'index']);
    Route::get('audio', [AudioController::class, 'index']);
    Route::get('community/posts', [CommunityController::class, 'posts']);
    Route::get('reviews', [ReviewController::class, 'index']);
    Route::get('courses', [CourseController::class, 'index']);
    Route::get('courses/{course}', [LearningController::class, 'show']);
    Route::get('dictionary', [DictionaryController::class, 'index']);
    Route::get('dictionary/{lexicalEntry}', [DictionaryController::class, 'show']);
    Route::get('exports/languages', ExportController::class);
    Route::post('ai/query', AiController::class)->middleware('throttle:ai');
    Route::post('analytics/events', [AnalyticsController::class, 'store']);
    Route::get('search', SearchController::class);
    Route::get('languages/{language}/statistics', [StatisticsController::class, 'language']);
    Route::get('languages/{language}/scripts', [LinguisticsController::class, 'scripts']);
    Route::get('languages/{language}/grammar', [LinguisticsController::class, 'grammar']);
    Route::get('scripts/{script}', [LinguisticsController::class, 'script']);
    Route::middleware('auth:sanctum')->group(function () {
        Route::post('languages', [LanguageController::class, 'store']);
        Route::post('dialects', [DialectController::class, 'store']);
        Route::post('contributions', [ContributionController::class, 'store']);
        Route::post('contributions/{contribution}/submit', [ContributionController::class, 'submit']);
        Route::post('contributions/{contribution}/publish', [ContributionController::class, 'publish']);
        Route::post('reviews', [ReviewController::class, 'store']);
        Route::post('dictionary', [DictionaryController::class, 'store']);
        Route::post('sources', [SourceController::class, 'store']);
        Route::post('audio', [AudioController::class, 'store']);
        Route::post('community/posts', [CommunityController::class, 'storePost']);
        Route::post('community/posts/{post}/comments', [CommunityController::class, 'comment']);
        Route::post('community/reports', [CommunityController::class, 'report']);
        Route::get('moderation/reports', [CommunityController::class, 'reports']);
        Route::get('admin/statistics', [StatisticsController::class, 'admin']);
        Route::get('admin/audit-logs', [AuditLogController::class, 'index']);
        Route::post('moderation/reports/{report}/resolve', [CommunityController::class, 'resolveReport']);
        Route::get('me/progress', [LearningController::class, 'myProgress']);
        Route::post('me/progress', [LearningController::class, 'progress']);
        Route::get('me/reputation', [AnalyticsController::class, 'reputation']);
    });
});
